package com.example.movies.screens.families

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier

@Composable
fun FamiliesScreen(
    modifier: Modifier = Modifier
) {
    Column(
        modifier = Modifier
            .verticalScroll(rememberScrollState())
    ) {
        Text("Families")
        Text("")
        Text("")
        Text("===== A =====")
        Text("Aeon")
        Text("Afziaka")
        Text("Agathion")
        Text("Alghollthu")
        Text("Aluum")
        Text("Anadi")
        Text("Android")
        Text("Angel")
        Text("Animated Bones")
        Text("Animated Object")
        Text("Ankhrav")
        Text("Ant")
        Text("Anugobu")
        Text("Ape")
        Text("Arboreal")
        Text("Archon")
        Text("Asura")
        Text("Aukashungi")
        Text("Azarketi")
        Text("Azata")
        Text("")

        Text("===== B =====")
        Text("Badger")
        Text("Bandersnatch")
        Text("Barghest")
        Text("Basilisk")
        Text("Bat")
        Text("Bear")
        Text("Beaver")
        Text("Beetle")
        Text("Beheaded")
        Text("Bhanyada")
        Text("Biloko")
        Text("Blackfrost Dead")
        Text("Blightburn Genies")
        Text("Bloodseeker")
        Text("Boar")
        Text("Bogeyman")
        Text("Boggard")
        Text("Bone Skipper")
        Text("Bore Worm")
        Text("Brughadatch")
        Text("Bugbear")
        Text("")

        Text("===== C =====")
        Text("Caligni")
        Text("Cat")
        Text("Catfolk")
        Text("Cave Worm")
        Text("Cecaelila")
        Text("Centipede")
        Text("Changelin")
        Text("Charau-ka")
        Text("Clockworks")
        Text("Cobblemite")
        Text("Cockroach")
        Text("Contemplative of Ashok")
        Text("Couatl")
        Text("Crab")
        Text("Crawling Hand")
        Text("Crocodile")
        Text("Cyclops")
        Text("")

        Text("===== D =====")
        Text("Daemon")
        Text("Darvakka")
        Text("Deadly Flora")
        Text("Deadly Puffball")
        Text("Deathless Acolyte")
        Text("Deep Gnome")
        Text("Demon")
        Text("Demon Throng")
        Text("Dero")
        Text("Devil")
        Text("Dhampir")
        Text("Dhuthorex")
        Text("Dinosaur")
        Text("Div")
        Text("Divine Warden")
        Text("Dog")
        Text("Dolphin")
        Text("Dragon, Black")
        Text("Dragon, Blue")
        Text("Dragon, Brass")
        Text("Dragon, Brine")
        Text("Dragon, Bronze")
        Text("Dragon, Chromatic")
        Text("Dragon, Cloud")
        Text("Dragon, Copper")
        Text("Dragon, Crystal")
        Text("Dragon, Forest")
        Text("Dragon, Gold")
        Text("Dragon, Green")
        Text("Dragon, Imperial")
        Text("Dragon, Magma")
        Text("Dragon, Metallic")
        Text("Dragon, Primal")
        Text("Dragon, Red")
        Text("Dragon, Sea")
        Text("Dragon, Silver")
        Text("Dragon, Sky")
        Text("Dragon, Sovereign")
        Text("Dragon, Umbral")
        Text("Dragon, Underworld")
        Text("Dragon, White")
        Text("Dragonfly")
        Text("Drake")
        Text("Drow")
        Text("Duergar")
        Text("")

        Text("===== E =====")
        Text("Eagle")
        Text("Eel")
        Text("Elder Thing")
        Text("Elemental, Air")
        Text("Elemental, Earth")
        Text("Elemental, Fire")
        Text("Elemental, Mephit")
        Text("Elemental, Metal")
        Text("Elemental, Water")
        Text("Elemental, Wisp")
        Text("Elemental, Wood")
        Text("Elephant")
        Text("Elk")
        Text("Ennosite")
        Text("Eurypterid")
        Text("")

        Text("===== F =====")
        Text("Facetbound")
        Text("Fetch")
        Text("Fetchling")
        Text("Fish")
        Text("Flea")
        Text("Fleshforged")
        Text("Fleshwarp")
        Text("Fly")
        Text("Flytrap")
        Text("Formian")
        Text("Fox")
        Text("Frog")
        Text("")

        Text("===== G =====")
        Text("Gargoyle")
        Text("Gathlain")
        Text("Genie")
        Text("Geniekin")
        Text("Ghoran")
        Text("Ghost")
        Text("Ghoul")
        Text("Giant")
        Text("Giant Bee")
        Text("Gibtas")
        Text("Gigantic Ant")
        Text("Girtablilu")
        Text("Gnoll")
        Text("Goblin")
        Text("Golem")
        Text("Gorga")
        Text("Graveknight")
        Text("Gremlin")
        Text("Grim Reaper")
        Text("Grioth")
        Text("Grippli")
        Text("Guardian Beast")
        Text("")

        Text("===== H =====")
        Text("Hag")
        Text("Hantu")
        Text("Harrowkin")
        Text("Hell Hound")
        Text("Herecite")
        Text("Herexen")
        Text("Hippocampus")
        Text("Hippopotamus")
        Text("Hobgoblin")
        Text("Horse")
        Text("House Spirit")
        Text("Hyena")
        Text("")

        Text("===== I =====")
        Text("Ikeshti")
        Text("")

        Text("===== J =====")
        Text("Jellyfish")
        Text("")

        Text("===== K =====")
        Text("Kaava")
        Text("Kami")
        Text("Karumzek")
        Text("Khefak")
        Text("Kitsune")
        Text("Kobold")
        Text("Kovintus")
        Text("")

        Text("===== L =====")
        Text("Lamia")
        Text("Leech")
        Text("Leshy")
        Text("Lich")
        Text("Lilu")
        Text("Linnorm")
        Text("Living Symbol")
        Text("Lizard")
        Text("Lizardfolk")
        Text("Locathah")
        Text("")

        Text("===== M =====")
        Text("Maftet")
        Text("Mana Wastes Mutant")
        Text("Mantis, Giant")
        Text("Merfolk")
        Text("Monkey")
        Text("Morlock")
        Text("Mortic")
        Text("Mosasaur")
        Text("Mosquito")
        Text("Mummy")
        Text("Munavri")
        Text("Munsahir")
        Text("")

        Text("===== N =====")
        Text("Naga")
        Text("Nagaji")
        Text("Necrohulk")
        Text("Nightmare")
        Text("Noppera-Bo")
        Text("Nymph")
        Text("")

        Text("===== O =====")
        Text("Octopus")
        Text("Ogre")
        Text("Oni")
        Text("Ooze")
        Text("Opossum")
        Text("Orc")
        Text("Owb")
        Text("Owlbear")
        Text("")

        Text("===== P =====")
        Text("Paaridar")
        Text("Phantom")
        Text("Planar Scion")
        Text("Protean")
        Text("Psychopomp")
        Text("Pterosaur")
        Text("")

        Text("===== Q =====")
        Text("Qlippoth")
        Text("")

        Text("===== R =====")
        Text("Rakshasa")
        Text("Ram")
        Text("Rat")
        Text("Ratajin")
        Text("Ratfolk")
        Text("Raven")
        Text("Ravener")
        Text("Ray")
        Text("Redcap")
        Text("Revenant")
        Text("Rhinoceros")
        Text("Risen Pet")
        Text("")

        Text("===== S =====")
        Text("Sahkil")
        Text("Samsaran")
        Text("Saurian")
        Text("Scorpion")
        Text("Sea Devil")
        Text("Serpentfolk")
        Text("Seugathi")
        Text("Shabti")
        Text("Shadow")
        Text("Shanrigol")
        Text("Shark")
        Text("Shobhad")
        Text("Shoony")
        Text("Siabrae")
        Text("Siktempora")
        Text("Silverfish")
        Text("Sinsludge")
        Text("Sinspawn")
        Text("Skeleton")
        Text("Skelm")
        Text("Skin Beetle")
        Text("Skull Swarm")
        Text("Skunk")
        Text("Sloth")
        Text("Sluagh")
        Text("Snake")
        Text("Solifugid")
        Text("Somnalu")
        Text("Spawn of Rovagug")
        Text("Sphinx")
        Text("Spider")
        Text("Spirit Guide")
        Text("Sporeborn")
        Text("Sportlebore")
        Text("Spriggan")
        Text("Sprite")
        Text("Squid")
        Text("Squirrel")
        Text("Stheno")
        Text("Strix")
        Text("")

        Text("===== T =====")
        Text("Terra-Cotta Warrior")
        Text("Terror Bird")
        Text("Thatchling")
        Text("Thylacine")
        Text("Tick")
        Text("Titan")
        Text("Toad")
        Text("Tooth Fairy")
        Text("Trilobite")
        Text("Troll")
        Text("Tsukumogami")
        Text("Turtle")
        Text("")

        Text("===== U =====")
        Text("Urdefhan")
        Text("")

        Text("===== V =====")
        Text("Vampire")
        Text("Vampire, Jiang-Shi")
        Text("Vampire, Nosferatu")
        Text("Vampire, Strigoi")
        Text("Vampire, Vetalarana")
        Text("Vampire, Vrykolakas")
        Text("Vanara")
        Text("Velstrac")
        Text("Verdorite")
        Text("Vilderavn")
        Text("Virulak")
        Text("Vishkanya")
        Text("Visitant")
        Text("")

        Text("===== W =====")
        Text("Warg")
        Text("Wasp")
        Text("Wayang")
        Text("Weasel")
        Text("Werecreature")
        Text("Werecreature, Wereant")
        Text("Wight")
        Text("Wild Hunt")
        Text("Will-o'-Wisp")
        Text("Wolf")
        Text("Wolverine")
        Text("Worm That Walks")
        Text("Wraith")
        Text("Wyrmwraith")
        Text("Wyrwood")
        Text("")

        Text("===== X =====")
        Text("Xiomorn")
        Text("Xulgath")
        Text("")

        Text("===== Y =====")
        Text("Yellow Musk Creeper")
        Text("")

        Text("===== Z =====")
        Text("Zombie")
        Text("Zombie, Tar")
    }
}