package com.example.movies.screens.types

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier

@Composable
fun TypesScreen(
    modifier: Modifier = Modifier
) {
    Column(
        modifier = Modifier
            .verticalScroll(rememberScrollState())
    ) {
        Text("Types")
        Text("")
        Text("")
        Text("===== A =====")
        Text("Aasimar")
        Text("Aberration")
        Text("Acid")
        Text("Aeon")
        Text("Aesir")
        Text("Agathion")
        Text("Air")
        Text("Alchemical")
        Text("Amphibious")
        Text("Anadi")
        Text("Android")
        Text("Angel")
        Text("Animal")
        Text("Anugobu")
        Text("Aphorite")
        Text("Aquatic")
        Text("Arcane")
        Text("Archon")
        Text("Ardande")
        Text("Astral")
        Text("Asura")
        Text("Automaton")
        Text("Azarketi")
        Text("Azata")
        Text("")

        Text("===== B =====")
        Text("Beast")
        Text("Boggard")
        Text("")

        Text("===== C =====")
        Text("Caligni")
        Text("Catfolk")
        Text("Celestial")
        Text("Changeling")
        Text("Charau-ka")
        Text("Clockwork")
        Text("Cold")
        Text("Construct")
        Text("Couatl")
        Text("")

        Text("===== D =====")
        Text("Daemon")
        Text("Darvakka")
        Text("Demon")
        Text("Dero")
        Text("Devil")
        Text("Dhampir")
        Text("Dinosaur")
        Text("Div")
        Text("Divine")
        Text("Dragon")
        Text("Dream")
        Text("Drow")
        Text("Duergar")
        Text("Duskwalker")
        Text("Dwarf")
        Text("")

        Text("===== E =====")
        Text("Earth")
        Text("Electricity")
        Text("Elemental")
        Text("Elf")
        Text("Ethereal")
        Text("Evil")
        Text("Evocation")
        Text("")

        Text("===== F =====")
        Text("Fetchling")
        Text("Fey")
        Text("Fiend")
        Text("Fire")
        Text("Force")
        Text("Formian")
        Text("Fungus")
        Text("")

        Text("===== G =====")
        Text("Ganzi")
        Text("Genie")
        Text("Ghoran")
        Text("Ghost")
        Text("Ghoul")
        Text("Ghul")
        Text("Giant")
        Text("Gnoll")
        Text("Gnome")
        Text("Goblin")
        Text("Golem")
        Text("Gremlin")
        Text("Grioth")
        Text("Grippli")
        Text("")

        Text("===== H =====")
        Text("Hag")
        Text("Halfing")
        Text("Hantu")
        Text("Herald")
        Text("Hryngar")
        Text("Human")
        Text("Humanoid")
        Text("")

        Text("===== I =====")
        Text("Ifrit")
        Text("Ikeshti")
        Text("Illusion")
        Text("Incorporeal")
        Text("Inevitable")
        Text("")

        Text("===== K =====")
        Text("Kami")
        Text("Kashrishi")
        Text("Kitsune")
        Text("Kobold")
        Text("Kovintus")
        Text("")

        Text("===== L =====")
        Text("Leshy")
        Text("Light")
        Text("Lilu")
        Text("Lizardfolk")
        Text("Locathah")
        Text("")

        Text("===== M =====")
        Text("Mental")
        Text("Merfolk")
        Text("Metal")
        Text("Mindless")
        Text("Minion")
        Text("Monitor")
        Text("Morlock")
        Text("Mortic")
        Text("Mummy")
        Text("Munavri")
        Text("Mutant")
        Text("")

        Text("===== N =====")
        Text("Nagaji")
        Text("Necromancy")
        Text("Negative")
        Text("Nymph")
        Text("")

        Text("===== O =====")
        Text("Oni")
        Text("Ooze")
        Text("Orc")
        Text("Oread")
        Text("")

        Text("===== P =====")
        Text("Paaridar")
        Text("Petitioner")
        Text("Phantom")
        Text("Plant")
        Text("Poison")
        Text("Positive")
        Text("Primal")
        Text("Protean")
        Text("Psychopomp")
        Text("")

        Text("===== Q =====")
        Text("Qlippoth")
        Text("")

        Text("===== R =====")
        Text("Rakshasa")
        Text("Rare")
        Text("Ratajin")
        Text("Ratfolk")
        Text("")

        Text("===== S =====")
        Text("Sahkil")
        Text("Samsaran")
        Text("Sea Devil")
        Text("Serpentfolk")
        Text("Seugathi")
        Text("Shabti")
        Text("Shade")
        Text("Shadow")
        Text("Shapechanger")
        Text("Shoony")
        Text("Siktempora")
        Text("Skeleton")
        Text("Skelm")
        Text("Skulk")
        Text("Soulbound")
        Text("Spirit")
        Text("Sporeborn")
        Text("Spriggan")
        Text("Sprite")
        Text("Stheno")
        Text("Strix")
        Text("Suli")
        Text("Swarm")
        Text("Sylph")
        Text("")

        Text("===== T =====")
        Text("Talos")
        Text("Tane")
        Text("Tanggal")
        Text("Tengu")
        Text("Tiefling")
        Text("Time")
        Text("Titan")
        Text("Troll")
        Text("Troop")
        Text("")

        Text("===== U =====")
        Text("Uncommon")
        Text("Undead")
        Text("Undine")
        Text("Unique")
        Text("Urdefhan")
        Text("")

        Text("===== V =====")
        Text("Vampire")
        Text("Vanara")
        Text("Velstrac")
        Text("Vishkanya")
        Text("Vitality")
        Text("Void")
        Text("")

        Text("===== W =====")
        Text("Water")
        Text("Wayang")
        Text("Werecreature")
        Text("Wight")
        Text("Wild Hunt")
        Text("Wood")
        Text("Wraith")
        Text("Wyrwood")
        Text("")

        Text("===== X =====")
        Text("Xulgath")
        Text("")

        Text("===== Z =====")
        Text("Zombie")
        Text("")
    }
}